"use client";

import "./globals.css";
// import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import Navigation from "@/components/Navigation/Navigation";
import { Provider } from "react-redux";
import { store, persistor } from "./store";

// import { persistor, store } from './redux/store';
import { PersistGate } from "redux-persist/integration/react";
import Image from "next/image";

const nunito = Nunito_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className} suppressHydrationWarning={true}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <div className="min-h-screen">
              <main className="flex min-h-screen flex-col p-5">
                <div className="container mx-auto">
                  <Navigation />
                </div>

                {children}
              </main>
            </div>
          </PersistGate>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
